/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountRow: typeof import('./components/AccountRow.vue')['default']
    AccountsHeader: typeof import('./components/AccountsHeader.vue')['default']
    AccountsHint: typeof import('./components/AccountsHint.vue')['default']
    AccountsPage: typeof import('./components/AccountsPage.vue')['default']
    AccountsTable: typeof import('./components/AccountsTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
  }
}
